version: "2"

services: 
  django-apache2:
    build:
      context: .
      args:
        - APACHE_CERT_PATH=local/apache.crt
        - APACHE_KEY_PATH=local/apache.key
        - local/.env
    container_name: django-apache2
    ports:
      - '8005:80'
      - '3500:3500'
      - '8006:81'
      - '8007:443'
    volumes: 
      - ./www:/var/www/
    env_file:
      - local/.env