version: "2"

services: 
  django-apache2:
    build: .
    container_name: django-apache2
    ports:
      - '8005:80'
      - '3500:3500'
      - '8006:81'
      - '8007:443'
    volumes: 
      - ./www:/var/www/
