# Generated by Django 3.2.16 on 2023-12-11 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCSEProfile',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cse_first_name', models.CharField(max_length=255)),
                ('cse_last_name', models.CharField(max_length=255)),
                ('cse_email', models.EmailField(max_length=254)),
                ('cse_employee_type', models.CharField(max_length=255)),
                ('cse_username', models.CharField(max_length=255)),
                ('cse_role', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical cse profile',
                'verbose_name_plural': 'historical cse profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CSEProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cse_first_name', models.CharField(max_length=255)),
                ('cse_last_name', models.CharField(max_length=255)),
                ('cse_email', models.EmailField(max_length=254)),
                ('cse_employee_type', models.CharField(max_length=255)),
                ('cse_username', models.CharField(max_length=255)),
                ('cse_role', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
